spring:
  application:
    name: Just-Another-RPG-Server

rpg:
  server:
    details:
#      address: # Server URL / IP address
      port: ${grpc.server.port} # Server GRPC port
#      name: # Server display name
  backend:
#    address: URL
#    token: Backend string-based token

grpc:
  server:
    port: 9090
    negotiationType: PLAINTEXT
