spring:
  application:
    name: Just-Another-RPG-Server

rpg:
  loader:
    file-structure:
      tiles: ./asset/tile
      tilemaps: ./asset/tilemap
      worlds: ./asset/world
      world-contexts: ./config/world-contexts
  server:
    details:
#      address: # Server URL / IP address
      port: ${server.port} # Server GRPC port
#      name: # Server display name
  backend:
#    address: URL
#    token: Backend string-based token
