spring:
  datasource:
    url: jdbc:h2:mem:rpg
    username: rpg
    password: rpg
    driver-class-name: org.h2.Driver
    platform: h2
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8080

admin:
  token: 1234567890123456
