spring:
  application:
    name: rpg-backend
  datasource:
#    url:
#    username:
#    password:
    driver-class-name: org.postgresql.Driver
    platform: postgres
  jpa:
    hibernate.ddl-auto: none
    dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    change-log: classpath:db/changelog/changelog-master.yml

#auth:
#  type: # Enum: auth-gateway
#  auth-gateway:
#    address: # URL: http://some-url.org:8855/
#    realm-name: # Realm name: some-realm
#    token: # String-based token
