spring:
  application:
    name: rpg-backend
  datasource:
#    jdbc-url:
#    username:
#    password:
    driver-class-name: org.postgresql.Driver
    platform: postgres
  jpa:
    dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

management:
  server:
    port: 8085
