spring:
  datasource:
    url: jdbc:h2:mem:rpg-backend
    username: rpg
    password: rpg
    driver-class-name: org.h2.Driver
    platform: h2
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

auth:
  type: internal
  auth-gateway:
    address: http://localhost:8080/
    token: ___localtoken___
    realm-name: local-rpg
