spring:
  datasource:
    url: jdbc:h2:file:./rpg-backend
    username: rpg
    password: rpg
    driver-class-name: org.h2.Driver
    platform: h2
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    contexts: local

server:
  port: 8081

auth:
  type: internal
